<?php

/**
 * @file
 * Contains wgc_entities.module.
 */

use Drupal\file\Entity\File;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wgc_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wgc_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom entities') . '</p>';
      return $output;

    default:
  }
}
